### ISSUE TITLE
Testing Chapter

### ISSUE THREAD

**Issue by martin-vlacil** [diversiwaver/aFRR-NET#92] opened 2022-12-20 08:17 UTC
- [x] Testing Introduction @martin-vlacil 
- [x] Implementation Details @martin-vlacil 
- [x] Scaffolding/Mocking @martin-vlacil 
- [x] Ad-hoc Testing @martin-vlacil 
- [x] Testing - NUnit instead of smt else @martin-vlacil

**Comment by martin-vlacil** [comment] 2022-12-21 11:53
wrote to all the chapters, some of them like adhoc testing need revisiting once we actually reach the part where we adhoc test much more for example with ui or api testing

![Image](https://user-images.githubusercontent.com/75024378/208899096-42028a1d-a3b3-4933-8365-53078c3e1439.png)

**Comment by mette-thorhauge** [comment] 2022-12-29 12:40
Upon reading the chapter @WrexBG and I have agreed, that it feels as if the introduction is missing a general introduction to the theory behind at least the three types of testing we will be doing: 

- [ ] Unit tests
- [ ] Integration tests 
- [ ] Ad hoc testing

We have therefore "un-ticked" the box for the testing introduction.
We have also "un-ticked" the box for ad-hoc testing, as it contains parts that talk about further explanation being needed. If these should not be written now, then they need to be moved to a separate Work Item/Issue here in Github, and be linked to the check-box matching it, before closing this issue.

**Comment by mette-thorhauge** [comment] 2023-01-03 18:55
I have now filled in the extra information. I would love to supply the ad-hoc testing part of the chapter with some screenshots from Swagger if people find it necessary. Also, if we agree on using Postman for further ad-hoc testing, I would love to add a few lines about this, followed by a screenshot as well.

**Comment by mirodmarinov** [comment] 2023-01-07 08:56
Read through it and I agree, it would be nice to add more to the Ad-hoc testing. Missing:

- [ ] Swagger tests with screenshots
- [ ] Postman tests with screenshots
- [ ] Grafana screenshots?

**Comment by WrexBG** [comment] 2023-01-07 17:02
We can also give some examples of integration tests since we have that in 2 places
Would be nice to show some basic Benchmark / Performance Testing
And we can also find a place to talk about Moq and creating mocks on the spot.

**Comment by mirodmarinov** [comment] 2023-01-11 08:43
I technically wrote a bit about postman and added screenshots from Swagger, but I don't have any postman screenshots so if anyone can add those, or just complete it without it.

**Comment by mirodmarinov** [comment] 2023-01-11 09:08
Also, resolve task #149 with this one

**Comment by mette-thorhauge** [comment] 2023-01-11 09:32
I have read the changes and think the issue can be closed once @WrexBG has finished reviewing it

**Comment by WrexBG** [comment] 2023-01-11 10:04
I added a little paragraph for Integration testing with an image


![Image](https://user-images.githubusercontent.com/40688355/211776962-9b3a6554-cd2c-4213-be6a-b1702fa50aa3.png)

The other stuff is good

**Comment by mette-thorhauge** [comment] 2023-01-11 11:11
I have read the changes and I think the issue is ready to be closed.

**Closed** 2023-01-11 11:11 UTC
